---
- ansible.builtin.debug:
    msg: "{{ item.key }} - {{ item.value['dns-01'].record[:-1 - (item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1]) | length] }} - {{ item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1] }} - {{ item.value['dns-01'].resource_value }}"
  loop: "{{ acme_challenges.challenge_data|dict2items }}"
- name: Create DNS Record
  ansible.builtin.uri:
    url: "https://api.godaddy.com/v1/domains/{{ item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1] }}/records"
    method: PATCH
    body_format: json
    status_code: [200]
    return_content: true
    headers:
      Content-Type: application/json
      Authorization: "sso-key {{ godaddy_api_key }}:{{ godaddy_api_secret }}"
    body:
      - name: "{{ item.value['dns-01'].record[:-1 - (item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1]) | length] }}"
        data: "{{ item.value['dns-01'].resource_value }}"
        type: TXT
        ttl: 600
  loop: "{{ acme_challenges.challenge_data|dict2items }}"
  register: response
# - ansible.builtin.debug:
#     msg: "{{ response }}"