---
- ansible.builtin.debug:
    msg: "{{ item.key }} - {{ item.value['dns-01'].record[:-1 - (item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1]) | length] }} - {{ item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1] }} - {{ item.value['dns-01'].resource_value }}"
  loop: "{{ challenge.challenge_data|dict2items }}"
  delegate_to: localhost
- name: Delete DNS Record
  ansible.builtin.uri:
    url: "https://api.godaddy.com/v1/domains/{{ item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1] }}/records/TXT/{{ item.value['dns-01'].record[:-1 - (item.value['dns-01'].record.split('.')[-2] + '.' + item.value['dns-01'].record.split('.')[-1]) | length] }}"
    method: DELETE
    status_code: [204]
    return_content: true
    headers:
      Content-Type: application/json
      Authorization: "sso-key {{ godaddy_api_key }}:{{ godaddy_api_secret }}"
  loop: "{{ challenge.challenge_data|dict2items }}"
  register: response
  delegate_to: localhost
# - ansible.builtin.debug:
#     msg: "{{ response }}"