---
- name: Sending an e-mail with certificate
  community.general.mail:
    host: smtp.lcmchealth.org
    port: 25
    from: ansible@lcmchealth.org (Ansible)
    to: "{{ email_recipient }}"
    subject: Ansible Generated Certificate
    body: "The password for the attached certificate is {{ random_password}}"
    attach: "/tmp/{{ working_directory }}/{{ certname }}.pfx"
  delegate_to: localhost