---
- name: "Waiting for \"{{ dns_value }}\" to appear in TXT record for {{ dns_record }}"
  ansible.builtin.debug:
    #msg: "{{ query('community.dns.lookup', dns_record, type='TXT', server='8.8.8.8') }}"
    msg: "{{ (lookup('community.general.dig', dns_record, '@8.8.8.8', qtype='TXT')).split(',') }}"
  register: dns_response
  until: dns_value in dns_response.msg
  retries: 3
  delay: 60
  ignore_errors: true