---
- ansible.builtin.include_tasks: resolve_txt_record.yml
  vars:
    dns_record: "{{ dns.value['dns-01'].record }}."
    dns_value: "{{ dns.value['dns-01'].resource_value }}"
  loop: "{{ challenge.challenge_data|dict2items }}"
  loop_control:
    loop_var: dns